# Generated by Django 3.0.2 on 2020-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('mdp', models.CharField(max_length=16)),
                ('login', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materiaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('important', models.TextField()),
                ('description', models.TextField()),
                ('infoGeneral', models.TextField()),
            ],
        ),
    ]
