# Generated by Django 3.0.2 on 2020-01-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_admin_materiaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('chefProjet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetMateriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.Materiaux')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.Projet')),
            ],
        ),
        migrations.CreateModel(
            name='PersonneProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.Personne')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.Projet')),
            ],
        ),
    ]
