# Generated by Django 3.0.2 on 2020-02-23 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comptes', '0004_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='type',
        ),
        migrations.AlterField(
            model_name='personneprojet',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projet',
            name='chefProjet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
