# Generated by Django 3.0.2 on 2020-01-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='type',
        ),
    ]
